apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sample
  namespace: tomcat-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-sample-dev
  template:
    metadata:
      labels:
        app: nginx-sample-dev
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80

