apiVersion: v1
kind: Service
metadata:
  name: nginx-sample
  namespace: tomcat-dev
spec:
  type: NodePort
  selector:
    app: nginx-sample-dev
  ports:
    - port: 80           # Cluster port
      targetPort: 80     # Container port
      nodePort: 30098s   # NodePort for kind

